version: '3'

services:
  # Service pour le backend
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=${MONGODB_URI}
      - JWT_SECRET=${JWT_SECRET}
      - PORT=5000
    restart: unless-stopped
    env_file:
      - ./.env

  # Service pour le frontend (à décommenter quand vous êtes prêt à l'ajouter)
  # frontend:
  #   build: ./frontend
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - backend
  #   environment:
  #     - REACT_APP_API_URL=http://backend:5000
  #   restart: unless-stopped
