{
  "services": [
    {
      "type": "web",
      "name": "cardzone-backend",
      "env": "docker",
      "dockerfilePath": "./Dockerfile",
      "plan": "free",
      "region": "oregon",
      "envVars": [
        {
          "key": "NODE_ENV",
          "value": "production"
        },
        {
          "key": "PORT",
          "value": "10000"
        },
        {
          "key": "MONGODB_URI",
          "fromDatabase": {
            "name": "cardzone-mongodb",
            "property": "connectionString"
          }
        },
        {
          "key": "JWT_SECRET",
          "generateValue": true
        },
        {
          "key": "FRONTEND_URL",
          "value": "https://cardzone-frontend.onrender.com"
        }
      ]
    }
  ],
  "databases": [
    {
      "name": "cardzone-mongodb",
      "databaseName": "cardzone",
      "user": "cardzone",
      "plan": "free"
    }
  ]
}