name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build Docker image
        run: docker build -t monapp-ci:$GITHUB_SHA -f backend/Dockerfile ./backend

  test:
    runs-on: ubuntu-latest
    needs: build
    services:
      mongodb:
        image: mongo:6
        ports:
          - 27017:27017
        options: >-
          --health-cmd "echo 'db.runCommand({serverStatus:1}).ok' | mongo --quiet | grep 1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Create env file for backend tests
        run: |
          echo "MONGODB_URI=mongodb://localhost:27017/cardzone_test" > backend/.env
          echo "JWT_SECRET=test_secret_for_ci" >> backend/.env
          echo "PORT=5050" >> backend/.env
          echo "NODE_ENV=test" >> backend/.env
      - name: Install backend dependencies with bcryptjs
        working-directory: ./backend
        run: |
          npm uninstall bcrypt
          npm install bcryptjs
          # Modification temporaire des imports bcrypt → bcryptjs
          find . -type f -name "*.js" -exec sed -i 's/require("bcrypt")/require("bcryptjs")/g' {} \;
          npm install
      - name: Run backend tests
        working-directory: ./backend
        run: |
          npm test
      - name: Run frontend tests
        working-directory: ./frontend
        run: |
          npm install
          npm test -- --watchAll=false --passWithNoTests

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Deploy (Simulation)
        run: echo "Deploy done for commit $GITHUB_SHA"