name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build Docker image
        run: docker build -t monapp-ci:$GITHUB_SHA .

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Run tests
        run: |
          npm install
          npm test

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Deploy (Simulation)
        run: echo "Deploy done for commit $GITHUB_SHA"